// Generated by scripts/gen-tools.ts from the Rust JSON Schemas. Do not edit by hand:
// run `bun run gen` after changing a tool or app command, and commit the result.

import { callApp, callTool } from "./bridge";

/** A script plus `dry_run`. */
export type AttachScriptInput = {
  /** Report what would happen without doing it. */
  dry_run?: boolean;
  /** Script file name. */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `attach_script`. */
export type AttachScriptOutput = {
  actions: Array<Action>;
  app: string;
  /** False on a dry run. */
  applied: boolean;
  event: string;
  /** How to apply the change on macOS; absent on a dry run. */
  note?: string | null;
  /** What the event pointed at before; absent when it was free. */
  replaces?: AttachState | null;
  script: string;
};

/** A script in a profile. */
export type CheckScriptInput = {
  /** Script file name, e.g. `on_copy_complete.py`. */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `check_script`. */
export type CheckScriptOutput = {
  /** Why the manifest's app or event is not in the catalog, if so. */
  catalog_error: string | null;
  /** The parsed manifest, or null. */
  manifest: Manifest | null;
  /** Script file name. */
  name: string;
  /** True when nothing above is a problem. */
  ok: boolean;
  /** Why the script's `import hedgebuddy` would fail, if so. */
  package_problem: string | null;
  /** Profile name. */
  profile: string;
  /** The interpreter used for the compile check. */
  python: string | null;
  /** Whether a Python compile check ran. */
  syntax_checked: boolean;
  /** The compile error, if any. */
  syntax_error: string | null;
  /** Requirements the profile does not meet. */
  unmet: Array<RequirementIssue>;
};

/** An app event plus `dry_run`. */
export type ClearStaleAttachmentInput = {
  /** Catalog app id. */
  app: string;
  /** Report what would change without changing it. */
  dry_run?: boolean;
  /** Event id from describe_app, e.g. FileCopyCompleted. */
  event: string;
};

/** Result of `clear_stale_attachment`. */
export type ClearStaleAttachmentOutput = {
  /** The changes to the Hedge app's settings. */
  actions: Array<Action>;
  /** Catalog app id. */
  app: string;
  /** False on a dry run. */
  applied: boolean;
  /** Event id. */
  event: string;
  /** How to apply the change on macOS; absent on a dry run. */
  note?: string | null;
};

/** Arguments of `create_profile`. */
export type CreateProfileInput = {
  /** Free text shown to the operator. */
  description?: string;
  /** Lowercase letters, digits and dashes, e.g. `commercial-one-day`. */
  name: string;
};

/** Result of `create_profile`. */
export type CreateProfileOutput = {
  /** Whether it became the active profile (the first one does). */
  active: boolean;
  /** The new, empty profile. */
  profile: Profile;
};

/** Arguments of `delete_profile`. */
export type DeleteProfileInput = {
  /** Report what would be deleted without deleting. */
  dry_run?: boolean;
  /** Profile name. */
  name: string;
};

/** Result of `delete_profile`. */
export type DeleteProfileOutput = {
  /** App events attached to its scripts. */
  attached_to: Array<ScriptEvent>;
  /** Always true. */
  dry_run: boolean;
  /** What would be deleted. */
  would_delete: ProfileDeletion;
} | {
  /** The active profile afterwards. */
  active: string | null;
  /** App events that pointed at its scripts. */
  attached_to: Array<ScriptEvent>;
  /** The deleted profile's name. */
  deleted: string;
};

/** A script plus `dry_run`. */
export type DeleteScriptInput = {
  /** Report what would happen without doing it. */
  dry_run?: boolean;
  /** Script file name. */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `delete_script`. */
export type DeleteScriptOutput = {
  /** App events attached to it. */
  attached_to: Array<AppEvent>;
  /** Always true. */
  dry_run: boolean;
  /** The script that would be deleted. */
  would_delete: ScriptRef;
} | {
  /** Script file name. */
  deleted: string;
  /** App events that still point at the deleted file. */
  left_attached: Array<AppEvent>;
  /** Profile name. */
  profile: string;
};

/** Arguments of `delete_var`. */
export type DeleteVarInput = {
  /** Report what would be deleted without deleting. */
  dry_run?: boolean;
  /** Variable name. */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `delete_var`. */
export type DeleteVarOutput = {
  /** Always true. */
  dry_run: boolean;
  /** The variable that would be deleted. */
  would_delete: VarDeletion;
} | {
  /** Variable name. */
  deleted: string;
  /** Profile name. */
  profile: string;
};

/** An app id. */
export type DescribeAppInput = {
  /** Catalog app id: offshoot, foolcat, editready or canister. */
  app: string;
};

/** Everything an agent needs about one app: its status, its full catalog entry, and its resolved files. */
export type DescribeAppOutput = {
  files: ResolvedFiles;
  manifest: AppManifest;
  status: AppStatus;
};

/** A script plus `dry_run`. */
export type DetachScriptInput = {
  /** Report what would happen without doing it. */
  dry_run?: boolean;
  /** Script file name. */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `detach_script`. */
export type DetachScriptOutput = {
  /** The changes to the Hedge app's settings. */
  actions: Array<Action>;
  /** False on a dry run. */
  applied: boolean;
  /** How to apply the change on macOS; absent on a dry run. */
  note?: string | null;
  /** Profile name. */
  profile: string;
  /** Script file name. */
  script: string;
};

/** Parameters of tools that take none. */
export type EnvironmentInput = Record<string, never>;

/** Result of `environment`. */
export type EnvironmentOutput = {
  /** The active profile. */
  active_profile: string | null;
  /** Hedge app status. */
  apps: Array<EnvironmentApp>;
  /** Catalog overrides. */
  catalog: CatalogState;
  /** The data folder. */
  data_dir: string;
  /** "windows" or "macos". */
  os: Os;
  /** The Python the Hedge apps use, if found. */
  python: PythonInfo | null;
  /** Whether that Python has this HedgeBuddy's `hedgebuddy` package. */
  python_package_matches: boolean;
  /** HedgeBuddy's version. */
  version: string;
};

/** Which profile (defaults to the active one). */
export type GetProfileInput = {
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `get_profile`. */
export type GetProfileOutput = {
  /** Whether it is the active profile. */
  active: boolean;
  /** The profile; secret values are never included. */
  profile: Profile;
  /** Its script file names. */
  scripts: Array<string>;
};

/** A run id. */
export type GetRunInput = {
  /** Run id from list_runs. */
  run_id: string;
};

/** A start record with its logs and (if any) its end record. */
export type GetRunOutput = {
  /** The app that triggered the run, if any. */
  app: string | null;
  /** Timestamp of the `end` record, if the run has ended. */
  ended_at: string | null;
  /** The event that triggered the run, if any. */
  event: string | null;
  /** The script's exit code, if the run has ended. */
  exit_code: number | null;
  /** Every `log` record for this run, in file order. */
  logs: Array<LogLine>;
  /** Name of the profile the run used. */
  profile: string;
  /** The run's unique ID, from the `start` record. */
  run_id: string;
  /** Name of the script that ran. */
  script: string;
  /** Timestamp of the `start` record. */
  started_at: string;
  /** The run's outcome, if it has ended. */
  status: RunStatus | null;
  /** A traceback, if the run ended with one. */
  traceback: string | null;
};

/** Arguments of `get_var`. */
export type GetVarInput = {
  /** Variable name (UPPER_SNAKE_CASE). */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
  /** Show the value if it is a secret. Only when the operator explicitly asks. */
  reveal?: boolean;
};

/** Result of `get_var`. */
export type GetVarOutput = {
  /** What the variable is for. */
  description: string;
  /** True when the variable has no value (for example a secret with nothing stored). */
  missing: boolean;
  /** Variable name. */
  name: string;
  /** Profile name. */
  profile: string;
  /** Variable type. */
  type: VarType;
  /** The value; `********` for a secret unless revealed; null when not set. */
  value: VarValueShape | null;
};

/** A folder or mount point. */
export type InspectVolumeInput = {
  /** Mount point from list_volumes, or any folder. */
  path: string;
};

/** Result of `inspect_volume`. */
export type InspectVolumeOutput = {
  /** What is on the volume or folder. */
  report: VolumeReport;
  /** The mounted volume at that path, if it is one. */
  volume: VolumeInfo | null;
};

/** Parameters of tools that take none. */
export type ListAppsInput = Record<string, never>;

/** Result of `list_apps`. */
export type ListAppsOutput = {
  /** Every catalog app and its status on this machine. */
  apps: Array<AppStatus>;
};

/** An app id. */
export type ListAttachmentsInput = {
  /** Catalog app id: offshoot, foolcat, editready or canister. */
  app: string;
};

/** Result of `list_attachments`. */
export type ListAttachmentsOutput = {
  /** Catalog app id. */
  app: string;
  /** Every event of the app and what it runs. */
  events: Array<EventAttachment>;
};

/** An app id. */
export type ListPresetsInput = {
  /** Catalog app id: offshoot, foolcat, editready or canister. */
  app: string;
};

/** Result of `list_presets`. */
export type ListPresetsOutput = {
  /** Catalog app id. */
  app: string;
  /** The app's presets. */
  presets: Array<Preset>;
  /** The selected preset, if known. */
  selected: string | null;
};

/** Parameters of tools that take none. */
export type ListProfilesInput = Record<string, never>;

/** Result of `list_profiles`. */
export type ListProfilesOutput = {
  /** The active profile, or null when there is none. */
  active: string | null;
  /** Every profile name. */
  profiles: Array<string>;
};

/** Arguments of `list_runs`. */
export type ListRunsInput = {
  /** Only runs triggered by this app. */
  app?: string | null;
  /** How many runs, newest first (default 20). */
  limit?: number | null;
  /** Only runs of this profile. */
  profile?: string | null;
  /** Only runs of this script file. */
  script?: string | null;
};

/** Result of `list_runs`. */
export type ListRunsOutput = {
  /** Runs, newest first. */
  runs: Array<Run>;
};

/** Which profile (defaults to the active one). */
export type ListScriptsInput = {
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `list_scripts`. */
export type ListScriptsOutput = {
  /** The profile listed. */
  profile: string;
  /** Its scripts with their manifests. */
  scripts: Array<ScriptInfo>;
};

/** Arguments of `list_vars`. */
export type ListVarsInput = {
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
  /** Show secret values. Only when the operator explicitly asks to see a secret. */
  reveal?: boolean;
};

/** Result of `list_vars`. */
export type ListVarsOutput = {
  /** Profile name. */
  profile: string;
  /** Its variables, sorted by name. */
  variables: Array<VarView>;
};

/** Parameters of tools that take none. */
export type ListVolumesInput = Record<string, never>;

/** Result of `list_volumes`. */
export type ListVolumesOutput = {
  /** Mounted volumes. */
  volumes: Array<VolumeInfo>;
};

/** Arguments of `read_app_log`. */
export type ReadAppLogInput = {
  /** Catalog app id. */
  app: string;
  /** How many lines from the end (default 50, max 500). */
  lines?: number | null;
  /** "callback" (URL command responses) or "event" (scripting and app log). */
  log: string;
};

/** Result of `read_app_log`. */
export type ReadAppLogOutput = {
  /** Catalog app id. */
  app: string;
  /** The last lines, oldest first. */
  lines: Array<string>;
  /** "callback" or "event". */
  log: LogKind;
};

/** A script in a profile. */
export type ReadScriptInput = {
  /** Script file name, e.g. `on_copy_complete.py`. */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `read_script`. */
export type ReadScriptOutput = {
  /** Script file name. */
  name: string;
  /** The profile the script belongs to. */
  profile: string;
  /** The full Python source. */
  source: string;
};

/** Arguments of `run_app_command`. */
export type RunAppCommandInput = {
  /** Catalog app id. */
  app: string;
  /** Commands in order. */
  commands: Array<CommandArg>;
  /** Set only after the operator approved the commands listed in requires_confirmation. */
  confirmed?: boolean;
  /** Return the planned URLs without opening them. */
  dry_run?: boolean;
  /** Seconds to wait for each response in the app's callback log (default 5, max 30, 0 = don't wait). */
  wait_seconds?: number | null;
};

/** Result of `run_app_command`. */
export type RunAppCommandOutput = {
  /** Always true. */
  dry_run: boolean;
  /** Always false. */
  executed: boolean;
  /** The URLs that would open. */
  plan: CommandPlan;
} | {
  /** Always false. */
  executed: boolean;
  /** What to do next. */
  message: string;
  /** The URLs that would open. */
  plan: CommandPlan;
  /** Commands the operator must approve. */
  requires_confirmation: Array<string>;
} | {
  /** Always true. */
  executed: boolean;
  /** The URLs opened and the app's responses. */
  outcome: CommandOutcome;
};

/** Arguments of `select_preset`. */
export type SelectPresetInput = {
  /** Catalog app id. */
  app: string;
  /** Return the planned change without making it. */
  dry_run?: boolean;
  /** Existing preset name. */
  name: string;
};

/** Result of `select_preset`. */
export type SelectPresetOutput = {
  /** The settings changes. */
  actions: Array<Action>;
  /** Catalog app id. */
  app: string;
  /** False on a dry run. */
  applied: boolean;
  /** The preset selected. */
  selected: string;
};

/** A profile name. */
export type SetActiveProfileInput = {
  /** Profile name. */
  name: string;
};

/** Result of `set_active_profile`. */
export type SetActiveProfileOutput = {
  /** The profile that is now active. */
  active: string;
};

/** Arguments of `set_var`. */
export type SetVarInput = {
  /** What the variable is for. Omit it to keep the existing variable's description. */
  description?: string | null;
  /** Variable name (UPPER_SNAKE_CASE). */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
  /** One of: string, secret, int, float, bool, path, url, string[], path[]. */
  type: string;
  /** The value, as JSON matching the type (secret and url are strings; string[] and path[] are arrays of strings). */
  value: unknown;
};

/** Result of `set_var`. Never includes the value. */
export type SetVarOutput = {
  /** The description now stored. */
  description: string;
  /** Variable name. */
  name: string;
  /** Profile name. */
  profile: string;
  /** Variable type. */
  type: VarType;
};

/** A profile plus `dry_run`. */
export type SyncAttachmentsInput = {
  /** Report what would change without changing it. */
  dry_run?: boolean;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
};

/** Result of `sync_attachments`. */
export type SyncAttachmentsOutput = {
  actions: Array<Action>;
  applied: boolean;
  attach: Array<SyncItem>;
  conflicts: Array<SyncConflict>;
  detach: Array<SyncItem>;
  /** How to apply the change on macOS; absent on a dry run. */
  note?: string | null;
  profile: string;
  skipped: Array<SyncSkip>;
};

/** Arguments of `write_preset`. */
export type WritePresetInput = {
  /** Catalog app id (presets exist for offshoot on Windows). */
  app: string;
  /** Next counter value, e.g. "003". */
  counter: string;
  /** Return the planned file without writing it. */
  dry_run?: boolean;
  /** Flatten source folders. */
  flatten_folders?: boolean;
  /** Destination folder pattern, e.g. ClientX/CAMERA/A{Source Counter}. */
  folder_pattern: string;
  /** Skip empty folders. */
  ignore_empty_folders?: boolean;
  /** Source label pattern, e.g. A{Source Counter}. */
  label_pattern: string;
  /** Preset name (file name without .hedge). */
  name: string;
  /** File rename pattern; empty keeps names. */
  rename_pattern?: string;
};

/** Result of `write_preset`. */
export type WritePresetOutput = {
  /** The file changes. */
  actions: Array<Action>;
  /** False on a dry run. */
  applied: boolean;
  /** What to do next. */
  next: string;
  /** The preset written (or planned). */
  preset: Preset;
};

/** Arguments of `write_script`. */
export type WriteScriptInput = {
  /** Script file name ending in `.py`. */
  name: string;
  /** Profile name; defaults to the active profile. */
  profile?: string | null;
  /** The full Python source, starting with the manifest docstring. */
  source: string;
};

/** Result of `write_script`. */
export type WriteScriptOutput = {
  /** App events still attached to the replaced script. */
  attached_to: Array<AppEvent>;
  /** The parsed manifest, or null when the script has none. */
  manifest: Manifest | null;
  /** Script file name. */
  name: string;
  /** The profile written to. */
  profile: string;
  /** Whether an existing script was replaced. */
  replaced: boolean;
  /** Requirements the profile does not meet. */
  unmet: Array<RequirementIssue>;
};

export interface ToolTypes {
  attach_script: { input: AttachScriptInput; output: AttachScriptOutput };
  check_script: { input: CheckScriptInput; output: CheckScriptOutput };
  clear_stale_attachment: { input: ClearStaleAttachmentInput; output: ClearStaleAttachmentOutput };
  create_profile: { input: CreateProfileInput; output: CreateProfileOutput };
  delete_profile: { input: DeleteProfileInput; output: DeleteProfileOutput };
  delete_script: { input: DeleteScriptInput; output: DeleteScriptOutput };
  delete_var: { input: DeleteVarInput; output: DeleteVarOutput };
  describe_app: { input: DescribeAppInput; output: DescribeAppOutput };
  detach_script: { input: DetachScriptInput; output: DetachScriptOutput };
  environment: { input: EnvironmentInput; output: EnvironmentOutput };
  get_profile: { input: GetProfileInput; output: GetProfileOutput };
  get_run: { input: GetRunInput; output: GetRunOutput };
  get_var: { input: GetVarInput; output: GetVarOutput };
  inspect_volume: { input: InspectVolumeInput; output: InspectVolumeOutput };
  list_apps: { input: ListAppsInput; output: ListAppsOutput };
  list_attachments: { input: ListAttachmentsInput; output: ListAttachmentsOutput };
  list_presets: { input: ListPresetsInput; output: ListPresetsOutput };
  list_profiles: { input: ListProfilesInput; output: ListProfilesOutput };
  list_runs: { input: ListRunsInput; output: ListRunsOutput };
  list_scripts: { input: ListScriptsInput; output: ListScriptsOutput };
  list_vars: { input: ListVarsInput; output: ListVarsOutput };
  list_volumes: { input: ListVolumesInput; output: ListVolumesOutput };
  read_app_log: { input: ReadAppLogInput; output: ReadAppLogOutput };
  read_script: { input: ReadScriptInput; output: ReadScriptOutput };
  run_app_command: { input: RunAppCommandInput; output: RunAppCommandOutput };
  select_preset: { input: SelectPresetInput; output: SelectPresetOutput };
  set_active_profile: { input: SetActiveProfileInput; output: SetActiveProfileOutput };
  set_var: { input: SetVarInput; output: SetVarOutput };
  sync_attachments: { input: SyncAttachmentsInput; output: SyncAttachmentsOutput };
  write_preset: { input: WritePresetInput; output: WritePresetOutput };
  write_script: { input: WriteScriptInput; output: WriteScriptOutput };
}

export type ToolName = keyof ToolTypes;

export const tools = {
  attachScript: (args: AttachScriptInput) => callTool("attach_script", args),
  checkScript: (args: CheckScriptInput) => callTool("check_script", args),
  clearStaleAttachment: (args: ClearStaleAttachmentInput) => callTool("clear_stale_attachment", args),
  createProfile: (args: CreateProfileInput) => callTool("create_profile", args),
  deleteProfile: (args: DeleteProfileInput) => callTool("delete_profile", args),
  deleteScript: (args: DeleteScriptInput) => callTool("delete_script", args),
  deleteVar: (args: DeleteVarInput) => callTool("delete_var", args),
  describeApp: (args: DescribeAppInput) => callTool("describe_app", args),
  detachScript: (args: DetachScriptInput) => callTool("detach_script", args),
  environment: (args: EnvironmentInput = {}) => callTool("environment", args),
  getProfile: (args: GetProfileInput = {}) => callTool("get_profile", args),
  getRun: (args: GetRunInput) => callTool("get_run", args),
  getVar: (args: GetVarInput) => callTool("get_var", args),
  inspectVolume: (args: InspectVolumeInput) => callTool("inspect_volume", args),
  listApps: (args: ListAppsInput = {}) => callTool("list_apps", args),
  listAttachments: (args: ListAttachmentsInput) => callTool("list_attachments", args),
  listPresets: (args: ListPresetsInput) => callTool("list_presets", args),
  listProfiles: (args: ListProfilesInput = {}) => callTool("list_profiles", args),
  listRuns: (args: ListRunsInput = {}) => callTool("list_runs", args),
  listScripts: (args: ListScriptsInput = {}) => callTool("list_scripts", args),
  listVars: (args: ListVarsInput = {}) => callTool("list_vars", args),
  listVolumes: (args: ListVolumesInput = {}) => callTool("list_volumes", args),
  readAppLog: (args: ReadAppLogInput) => callTool("read_app_log", args),
  readScript: (args: ReadScriptInput) => callTool("read_script", args),
  runAppCommand: (args: RunAppCommandInput) => callTool("run_app_command", args),
  selectPreset: (args: SelectPresetInput) => callTool("select_preset", args),
  setActiveProfile: (args: SetActiveProfileInput) => callTool("set_active_profile", args),
  setVar: (args: SetVarInput) => callTool("set_var", args),
  syncAttachments: (args: SyncAttachmentsInput = {}) => callTool("sync_attachments", args),
  writePreset: (args: WritePresetInput) => callTool("write_preset", args),
  writeScript: (args: WriteScriptInput) => callTool("write_script", args),
} as const;

/** Arguments of `activity`. */
export type ActivityInput = {
  /** How many records, newest first (default and maximum 200). */
  limit?: number | null;
};

/** Result of `activity`. */
export type ActivityOutput = {
  /** Claude's latest tool calls, newest first. */
  records: Array<ActivityRecord>;
};

/** Parameters of tools that take none. */
export type HomeSummaryInput = Record<string, never>;

/** Result of `home_summary`. */
export type HomeSummaryOutput = {
  /** The active profile, or null when there is none. */
  active_profile: string | null;
  /** Problems, most serious first, each linking to where it gets fixed. */
  attention: Array<AttentionItem>;
  /** Counts for the sidebar badges. */
  badges: SidebarBadges;
  /** The four numbers at the top of Home. */
  counts: HomeCounts;
  /** Every profile name. */
  profiles: Array<string>;
  /** The Python the Hedge apps use. */
  python: PythonStatus;
  /** Claude's latest tool calls, newest first. */
  recent_activity: Array<ActivityRecord>;
  /** The latest runs across all profiles, newest first. */
  recent_runs: Array<Run>;
  /** When the app was opened before this session (UTC, RFC 3339), or null on the first launch. Counts cover the runs since then, or every kept run (30 days) when null. */
  since: string | null;
};

/** Parameters of tools that take none. */
export type PreferencesGetInput = Record<string, never>;

/** Contents of `preferences.json`. */
export type PreferencesGetOutput = {
  /** The command "Open in editor" runs, or null for the system default. */
  editor_command: string | null;
  /** When the app was last opened (UTC, RFC 3339), or null. */
  last_opened: string | null;
  /** Storage format version; always 1. */
  version: number;
};

/** A change to [`Preferences`]: a key that is absent leaves its field alone, `null` clears it, a value sets it. */
export type PreferencesSetInput = {
  /** The editor command, or null for the system default. */
  editor_command?: string | null;
  /** When the app was last opened (UTC, RFC 3339), or null to clear. */
  last_opened?: string | null;
};

/** Contents of `preferences.json`. */
export type PreferencesSetOutput = {
  /** The command "Open in editor" runs, or null for the system default. */
  editor_command: string | null;
  /** When the app was last opened (UTC, RFC 3339), or null. */
  last_opened: string | null;
  /** Storage format version; always 1. */
  version: number;
};

export interface AppCommandTypes {
  activity: { input: ActivityInput; output: ActivityOutput };
  home_summary: { input: HomeSummaryInput; output: HomeSummaryOutput };
  preferences_get: { input: PreferencesGetInput; output: PreferencesGetOutput };
  preferences_set: { input: PreferencesSetInput; output: PreferencesSetOutput };
}

export type AppCommandName = keyof AppCommandTypes;

export const app = {
  activity: (args: ActivityInput = {}) => callApp("activity", args),
  homeSummary: (args: HomeSummaryInput = {}) => callApp("home_summary", args),
  preferencesGet: (args: PreferencesGetInput = {}) => callApp("preferences_get", args),
  preferencesSet: (args: PreferencesSetInput = {}) => callApp("preferences_set", args),
} as const;

/** One change HedgeBuddy would make outside its data directory. Plans return lists of these; nothing happens until [`Hedge::apply`] runs them, so every plan doubles as a dry run. Actions serialize (to show a dry run) but deliberately do not deserialize. Plans are produced by core; front ends must re-plan from the original arguments rather than accepting actions from a client. */
export type Action = {
  action: "registry_set";
  data: RegValue;
  key: string;
  value: string;
} | {
  action: "registry_delete";
  key: string;
  value: string;
} | {
  action: "workspace_prefs";
  path: string;
  set: {
    [key: string]: unknown;
  };
} | {
  action: "write_file";
  contents: string;
  path: string;
};

/** How a tool call ended. */
export type ActivityOutcome = "ok" | "error" | "needs_confirmation";

/** One line of `activity.jsonl`. */
export type ActivityRecord = {
  /** How it ended. */
  outcome: ActivityOutcome;
  /** What it acted on: the first of `name`, `script`, `run_id`, `event`, `app`, `profile` that the call passed, or null. */
  target: string | null;
  /** The tool's name. */
  tool: string;
  /** When the call finished (UTC, RFC 3339). */
  ts: string;
};

/** A Hedge app event. */
export type AppEvent = {
  /** Catalog app id. */
  app: string;
  /** Event id. */
  event: string;
};

/** `[app]`: identity of a Hedge app. */
export type AppInfo = {
  docs: string;
  id: string;
  name: string;
  requires_pro: boolean;
  scheme?: string | null;
};

/** One catalog file. */
export type AppManifest = {
  app: AppInfo;
  catalog_version: number;
  commands: Array<CommandSpec>;
  detect: PerOsDetect;
  events: Array<EventSpec>;
  files: PerOsFiles;
  presets: PerOsPresetsSpec;
  scripting: PerOsScripting;
  tested_against: string;
};

/** What HedgeBuddy knows about one Hedge app on this machine. */
export type AppStatus = {
  id: string;
  installed: boolean;
  name: string;
  newer_than_tested: boolean;
  requires_pro: boolean;
  scripting: ScriptingSupport;
  scripting_enabled: boolean | null;
  tested_against: string;
  version: string | null;
  warnings: Array<string>;
};

/** What an app event is attached to right now. */
export type AttachState = {
  path: string;
  profile: string;
  script: string;
  state: "attached";
} | {
  path: string;
  state: "external";
} | {
  path: string;
  state: "stale";
} | {
  path: string;
  state: "staged";
  workspace: string;
} | {
  state: "detached";
} | {
  note: string;
  state: "manual";
} | {
  state: "unsupported";
};

/** One row of "Needs attention". */
export type AttentionItem = {
  kind: "run_failed";
  /** The profile it ran with. */
  profile: string;
  /** Run id (links to `#/runs/<id>`). */
  run_id: string;
  /** Script file name. */
  script: string;
  /** When it started (UTC, RFC 3339). */
  started_at: string;
} | {
  /** How many more. */
  count: number;
  kind: "more_failed_runs";
} | {
  /** The type the profile declares, for a type mismatch. */
  actual: VarType | null;
  kind: "variable_issue";
  /** Variable name. */
  name: string;
  /** Missing or the wrong type. */
  problem: VariableProblem;
  /** The scripts that require it. */
  scripts: Array<string>;
  /** The type the scripts require. */
  type: VarType;
} | {
  /** Catalog app id. */
  app: string;
  /** The app's display name. */
  app_name: string;
  /** How many events. */
  count: number;
  kind: "stale_entries";
} | {
  /** The installed `hedgebuddy` version, if any. */
  installed: string | null;
  kind: "package_problem";
  /** Whether Python was found at all. */
  python_found: boolean;
  /** The version this HedgeBuddy needs. */
  required: string;
} | {
  /** Catalog app id. */
  app: string;
  /** The app's display name. */
  app_name: string;
  kind: "app_newer";
  /** The version HedgeBuddy was tested with. */
  tested_against: string;
  /** Installed version. */
  version: string;
} | {
  /** Catalog app id. */
  app: string;
  /** The app's display name. */
  app_name: string;
  /** How many of its events have a script attached. */
  events: number;
  kind: "scripting_off";
};

/** Which kind of card a volume looks like, and the evidence. */
export type CardGuess = {
  evidence: string;
  kind: string;
};

/** Catalog overrides in effect. */
export type CatalogState = {
  /** Why the overrides were ignored, if they were. */
  error: string | null;
  /** Apps whose catalog file is overridden from `<data>/catalog/`. */
  overridden: Array<string>;
};

/** One command of `run_app_command`. */
export type CommandArg = {
  /** Command id from describe_app, e.g. setSource. */
  command: string;
  /** Parameters as describe_app lists them; omit for none. */
  params?: {
    [key: string]: unknown;
  };
};

/** How a command is encoded as a URL. */
export type CommandForm = "url" | "action";

/** What happened when the URLs were opened. */
export type CommandOutcome = {
  plan: CommandPlan;
  responses: Array<string>;
};

/** The URLs a list of commands turns into, and which commands the operator should confirm first. */
export type CommandPlan = {
  app: string;
  confirm: Array<string>;
  urls: Array<string>;
};

/** `[[commands]]`: one URL-scheme command. */
export type CommandSpec = {
  confirm: boolean;
  description: string;
  form: CommandForm;
  id: string;
  list_separator?: string | null;
  params: {
    [key: string]: string;
  };
  platforms: Array<Os>;
};

/** `[detect.<os>]`: how to tell whether the app is installed. */
export type Detect = {
  app_path?: string | null;
  bundle_id?: string | null;
  registry_key?: string | null;
  version_value?: string | null;
};

/** One Hedge app in `environment`. */
export type EnvironmentApp = {
  /** Catalog app id. */
  id: string;
  /** Whether it is installed. */
  installed: boolean;
  /** Installed version. */
  version: string | null;
  /** Warnings such as a version newer than tested. */
  warnings: Array<string>;
};

/** One event's attachment. The state is flattened into the same object: `{"app": ..., "event": ..., "state": "attached", "path": ..., ...}`. */
export type EventAttachment = ({
  app: string;
  event: string;
}) & ({
  path: string;
  profile: string;
  script: string;
  state: "attached";
} | {
  path: string;
  state: "external";
} | {
  path: string;
  state: "stale";
} | {
  path: string;
  state: "staged";
  workspace: string;
} | {
  state: "detached";
} | {
  note: string;
  state: "manual";
} | {
  state: "unsupported";
});

/** `[[events]]`: one scripting event. */
export type EventSpec = {
  description: string;
  id: string;
  json_fields: Array<string>;
  payload: Array<string>;
  pref_name?: string | null;
  registry_name?: string | null;
};

/** `[files.<os>]`: app log files. */
export type Files = {
  callback_log?: string | null;
  event_log?: string | null;
};

/** The numbers at the top of Home. */
export type HomeCounts = {
  /** Of those, the runs that failed (status `failed` or `error`). */
  failed_since: number;
  /** Runs started since `since`, across all profiles. */
  runs_since: number;
  /** The active profile's scripts attached to (or staged for) an app event. */
  scripts_attached: number;
  /** The active profile's variables. */
  variables: number;
};

/** Which app log to read. */
export type LogKind = "callback" | "event";

/** One `log` record, reassociated with its run. */
export type LogLine = {
  /** The log message. */
  message: string;
  /** When the log line was written. */
  ts: string;
};

/** The parsed manifest block from a script's module docstring (spec section 6). `app` and `event` are free-form strings here; the schema's stricter patterns for known apps and events (`^[a-z][a-z0-9-]*$` and `^[A-Za-z][A-Za-z0-9]*$`) are enforced against the phase 2B catalog, not by this type. */
export type Manifest = {
  app?: string | null;
  event?: string | null;
  hedgebuddy: number;
  requires: {
    [key: string]: Requirement;
  };
};

/** The two supported desktop platforms. */
export type Os = "windows" | "macos";

/** A value that may differ between Windows and macOS. */
export type PerOsDetect = {
  macos?: Detect | null;
  windows?: Detect | null;
};

/** A value that may differ between Windows and macOS. */
export type PerOsFiles = {
  macos?: Files | null;
  windows?: Files | null;
};

/** A value that may differ between Windows and macOS. */
export type PerOsPresetsSpec = {
  macos?: PresetsSpec | null;
  windows?: PresetsSpec | null;
};

/** A value that may differ between Windows and macOS. */
export type PerOsScripting = {
  macos?: Scripting | null;
  windows?: Scripting | null;
};

/** The fields of an OffShoot preset (`<name>.hedge`) that HedgeBuddy reads and writes. */
export type Preset = {
  counter: string;
  flatten_folders: boolean;
  folder_pattern: string;
  ignore_empty_folders: boolean;
  label_pattern: string;
  name: string;
  rename_pattern: string;
};

/** `[presets.<os>]`: where presets live and how one is selected. */
export type PresetsSpec = {
  dir: string;
  location_override_value?: string | null;
  registry_key?: string | null;
  selected_value?: string | null;
};

/** Contents of `profile.json`. Variables are kept sorted by name. */
export type Profile = {
  description: string;
  name: string;
  variables: {
    [key: string]: Variable;
  };
  version: number;
};

/** What `delete_profile` would delete. */
export type ProfileDeletion = {
  /** Profile name. */
  profile: string;
  /** Its script file names. */
  scripts: Array<string>;
  /** How many variables it holds. */
  variables: number;
};

/** The interpreter Hedge apps use. */
export type PythonInfo = {
  executable: string;
  hedgebuddy: string | null;
  launcher: Array<string>;
  version: string;
};

/** The Python the Hedge apps use, for Home and Settings. */
export type PythonStatus = {
  /** Its path. */
  executable: string | null;
  /** Whether an interpreter was found. */
  found: boolean;
  /** The `hedgebuddy` version installed there, if any. */
  installed: string | null;
  /** What is wrong, in one sentence, or null. */
  problem: string | null;
  /** The version this HedgeBuddy needs. */
  required: string;
  /** Its version. */
  version: string | null;
};

/** A registry value HedgeBuddy reads or writes. */
export type RegValue = {
  data: string;
  type: "string";
} | {
  data: number;
  type: "dword";
};

/** One entry of a manifest's `requires` map. */
export type Requirement = {
  default?: unknown;
  description: string;
  type: VarType;
};

/** Why a profile does not satisfy a manifest. */
export type RequirementIssue = {
  kind: "missing";
  /** The missing variable's name. */
  name: string;
  /** The type the manifest requires. */
  ty: VarType;
} | {
  /** The type the profile actually declares. */
  actual: VarType;
  /** The type the manifest requires. */
  expected: VarType;
  kind: "type_mismatch";
  /** The variable's name. */
  name: string;
};

/** An app's file locations with `%VAR%` and `~` expanded for this machine. */
export type ResolvedFiles = {
  callback_log: string | null;
  event_log: string | null;
  presets_dir: string | null;
};

/** A start record with its logs and (if any) its end record. */
export type Run = {
  /** The app that triggered the run, if any. */
  app: string | null;
  /** Timestamp of the `end` record, if the run has ended. */
  ended_at: string | null;
  /** The event that triggered the run, if any. */
  event: string | null;
  /** The script's exit code, if the run has ended. */
  exit_code: number | null;
  /** Every `log` record for this run, in file order. */
  logs: Array<LogLine>;
  /** Name of the profile the run used. */
  profile: string;
  /** The run's unique ID, from the `start` record. */
  run_id: string;
  /** Name of the script that ran. */
  script: string;
  /** Timestamp of the `start` record. */
  started_at: string;
  /** The run's outcome, if it has ended. */
  status: RunStatus | null;
  /** A traceback, if the run ended with one. */
  traceback: string | null;
};

/** Status of a completed run. */
export type RunStatus = "ok" | "failed" | "error";

/** An app event attached to one of a profile's scripts. */
export type ScriptEvent = {
  /** Catalog app id. */
  app: string;
  /** Event id. */
  event: string;
  /** Script file name. */
  script: string;
};

/** One entry of a profile's `scripts/` folder with its parsed manifest, if any. */
export type ScriptInfo = {
  /** The script's parsed manifest, or `None` when it has no manifest block. */
  manifest: Manifest | null;
  /** Set when the file has a manifest block that does not parse. */
  manifest_error: string | null;
  /** The script's file name. */
  name: string;
};

/** A script in a profile. */
export type ScriptRef = {
  /** Script file name. */
  name: string;
  /** Profile name. */
  profile: string;
};

/** `[scripting.<os>]`: where script attachments live on that platform. */
export type Scripting = {
  enable_value: string;
  key: string;
  kind: "registry";
  value_pattern: string;
} | {
  enable_pref: string;
  kind: "helper_workspace";
  pref_pattern: string;
  workspace_dir: string;
  workspace_file: string;
} | {
  kind: "manual";
  note: string;
};

/** How scripts are attached for an app on this platform. */
export type ScriptingSupport = "registry" | "helper_workspace" | "manual" | "none";

/** Counts for the sidebar badges. */
export type SidebarBadges = {
  /** Hedge apps: events pointing at deleted scripts. */
  apps: number;
  /** Runs: failures since the last open. */
  runs: number;
  /** Settings: package problems (0 or 1). */
  settings: number;
  /** Variables: required variables missing or of the wrong type. */
  variables: number;
};

/** Several scripts of one profile target the same app event. */
export type SyncConflict = {
  app: string;
  event: string;
  scripts: Array<string>;
};

/** A script attached to (or detached from) an app event. */
export type SyncItem = {
  app: string;
  event: string;
  /** For an attach: what the event pointed at before (another script, an operator's own file, a missing file, or a staged workspace entry). Absent when the event was free, and for detaches. */
  replaces?: AttachState | null;
  script: string;
};

/** A script that could not be attached, and why. */
export type SyncSkip = {
  reason: string;
  script: string;
};

/** What `delete_var` would delete. */
export type VarDeletion = {
  /** Variable name. */
  name: string;
  /** Profile name. */
  profile: string;
  /** Variable type. */
  type: VarType;
};

/** The nine variable types. Serialized names are the schema's exact strings. */
export type VarType = "string" | "secret" | "int" | "float" | "bool" | "path" | "url" | "string[]" | "path[]";

/** A variable's JSON value, for the schema only: text (string, secret, path, url), a number (int, float), a flag (bool) or a list of strings (string[], path[]). */
export type VarValueShape = string | number | boolean | Array<string>;

/** A variable as the tools return it. */
export type VarView = {
  /** What the variable is for. */
  description: string;
  /** True when the variable has no value (for example a secret with nothing stored). */
  missing: boolean;
  /** Variable name. */
  name: string;
  /** Variable type. */
  type: VarType;
  /** The value; `********` for a secret unless revealed; null when not set. */
  value: VarValueShape | null;
};

/** One entry in `profile.json`'s `variables` map. */
export type Variable = {
  /** Free-text description shown to whoever edits the profile. */
  description: string;
  /** The variable's declared type. */
  type: VarType;
  /** The variable's value, typed per `ty`. `None` for a secret (whose value lives in `secrets.json`) or a variable with no value yet. */
  value?: unknown;
};

/** What is wrong with a required variable. */
export type VariableProblem = "missing" | "type_mismatch";

/** A mounted volume as the operating system reports it. */
export type VolumeInfo = {
  available_bytes: number;
  file_system: string;
  mount_point: string;
  name: string;
  removable: boolean;
  total_bytes: number;
};

/** What is on a volume. */
export type VolumeReport = {
  card: CardGuess | null;
  clip_count: number;
  media_bytes: number;
  root: string;
  top_level: Array<string>;
  truncated: boolean;
};
