// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVariable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddVariable'](arg1, arg2, arg3, arg4);
}

export function DeleteVariable(arg1) {
  return window['go']['main']['App']['DeleteVariable'](arg1);
}

export function GetSortedKeys() {
  return window['go']['main']['App']['GetSortedKeys']();
}

export function GetStoragePath() {
  return window['go']['main']['App']['GetStoragePath']();
}

export function GetVariables() {
  return window['go']['main']['App']['GetVariables']();
}

export function ImportSelectedVariables(arg1) {
  return window['go']['main']['App']['ImportSelectedVariables'](arg1);
}

export function LoadExternalVariables(arg1) {
  return window['go']['main']['App']['LoadExternalVariables'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenStorageFolder() {
  return window['go']['main']['App']['OpenStorageFolder']();
}

export function ReloadVariables() {
  return window['go']['main']['App']['ReloadVariables']();
}

export function UpdateVariable(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateVariable'](arg1, arg2, arg3, arg4, arg5);
}
