// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function AddVariable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteVariable(arg1:string):Promise<void>;

export function GetSortedKeys():Promise<Array<string>>;

export function GetStoragePath():Promise<string>;

export function GetVariables():Promise<Record<string, storage.Variable>>;

export function ImportSelectedVariables(arg1:Record<string, storage.Variable>):Promise<storage.ImportSummary>;

export function LoadExternalVariables(arg1:string):Promise<Record<string, storage.Variable>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenStorageFolder():Promise<void>;

export function ReloadVariables():Promise<void>;

export function UpdateVariable(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
